/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-podofo.h
 #	source generated by 4D Plugin Wizard
 #	Project : podofo
 #	author : miyako
 #	2020/12/11
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PODOFO_H
#define PLUGIN_PODOFO_H

#include "4DPluginAPI.h"

#include <cstdlib>
#include <cstdio>
#include <string>
#include <iostream>

#include "openssl/bio.h"
#include "openssl/evp.h"
#include "openssl/err.h"
#include "openssl/pem.h"
#include "openssl/ssl.h"
#include "openssl/x509.h"

#if defined(_WIN64)
#define fseeko _fseeki64
#define ftello _ftelli64
#else
#define fseeko fseek
#define ftello ftell
#endif

#include "podofo/podofo.h"

#include "4DPlugin-JSON.h"

#if __APPLE__
#import <CoreFoundation/CoreFoundation.h>
#import <Cocoa/Cocoa.h>
#import <AppKit/AppKit.h>
#endif

using namespace PoDoFo;

#include "C_BLOB.h"

#pragma mark -

void podofo_get_form(PA_PluginParameters params);
void podofo_set_form(PA_PluginParameters params);
void podofo_sign_document(PA_PluginParameters params);

static void set_color(PdfPainter *painter, PA_ObjectRef fieldObj);
static void get_rect(PA_ObjectRef annotationObj, double pageHeight, double *x, double *y, double *width, double *height);
static void set_annotation_properties(PdfAnnotation *annotation, PA_ObjectRef annotationObj);
static void set_text_properties(PdfAnnotation *annotation, PA_ObjectRef fieldObj, const PdfString &textValue, PdfDocument *document);
static void set_properties(PdfField *field, PA_ObjectRef fieldObj, PdfDocument *document);

#endif /* PLUGIN_PODOFO_H */
